spring.application.name=card
spring.datasource.url=jdbc:postgresql://localhost:5432/card_service_db
spring.datasource.username=panhasak
spring.datasource.password=panhasak12345
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8070

spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:8071

eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone= http://localhost:9000/eureka

# spring acutator and to exposes all end-point
management.endpoints.web.exposure.include=*

#configutaion info end-point
info.app.name = Card Microservice
info.app.description = Panhasak Bank Card App
info.app.version = 1.0.0
management.info.env.enabled=true